### ISSUE TITLE
404 Error on running the project.

### ISSUE THREAD

**Issue by nakul-shahdadpuri** [thec0sm0s/image-processor#3]
I just cloned and ran your project, it gave me a 404 error. I guess this is a bug. :)

**Comment by weibeu** [comment]
Hello @nakul-shahdadpuri sorry for the late response. My bad. I wasn't watching this repository so I didn't got notified of the new issues/PRs.

Assuming you received 404 error on visiting the root host (http://127.0.0.1:5000) and its okay. Because there is no UI or auto generated swagger docs or something like that. Its really simple API setup.
The actual API route is `/category/{ROUTE}` where `ROUTE` is class attribute of any meme or any image resource which is set manually. For example, for rip meme its `/memes/rip/`. Check tests directory which has some common and tested API endpoints.

Also I thanks for the PR! I will consider that and mark with `hacktoberfest-accepted` label.
